# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [3.6, 3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Tox and any other packages
      run: pip install tox
    - name: Run Tox
      # Run tox using the version of Python in `PATH`
      run: tox -e py

    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.3.0
      with:
        python-root-list: "pigz_python tests"
        # Set max line length to same as Black
        extra-pycodestyle-options: "--max-line-length=88"
        extra-flake8-options: "--max-line-length=88"
